const DEFAULT={
github:{repository:"nexgen999/evoX-CoreOS",dataRepository:"nexgen999/evoX-CoreOS",webuiRepository:"nexgen999/evoX-CoreOS-WebUI",branch:"main",user:"nexgen999",bio:"Passionné par le homebrew, le développement et les projets open source.",repos:"123"},
site:{name:"evoX Core OS",title:"evoX Core OS · WebUI"},
header:{logo:"./web/assets/logo.svg",subtitle:"WEBUI",actions:[
{label:"AIO Payloads (.zip)",url:"https://github.com/nexgen999/evoX-CoreOS/releases/download/latest/PS5_payloads_aio_latest.zip",icon:"download"},
{label:"AIO PKG (.zip)",url:"https://github.com/nexgen999/evoX-CoreOS/releases/download/latest/PS5_pkg_aio_latest.zip",icon:"download"},
{label:"GitHub",url:"https://github.com/nexgen999/evoX-CoreOS",icon:"github",iconOnly:true}]},
sidebar:{menus:[["home","Home","home"],["news","News","news"],["download","Download","download"],["store","Store","store"],["services","Services","services"],["docs","Documentation","docs"],["about","About","about"],["thanks","Remerciements","thanks"]],card:{title:"evoX Core OS",text:"One place. All your needs."}},
socials:[{label:"GitHub",url:"https://github.com/nexgen999",icon:"github"},{label:"X",url:"https://x.com/nexgen999",icon:"𝕏"},{label:"Bluesky",url:"https://bsky.app/profile/nexgen999.bsky.social",icon:"🦋"}],
home:{hero:{eyebrow:"evoX CORE OS",title:"Bienvenue sur evoX Core OS",text:"Un espace unique pour accéder à mes projets, ressources, news et bien plus encore. Explore, télécharge, découvre !",chips:["✦ Payloads PS5","▣ Store","◔ News RSS","▤ Documentation","◇ Open Source"]},welcomeTitle:"Bienvenue !",welcomeText:"Passionné par le homebrew, le développement et les projets open source.",thanksTitle:"Un immense merci !",thanksText:"Merci à toutes les personnes qui me soutiennent, qui m'encouragent et qui font vivre cette communauté. Vous êtes géniaux !",slogan:"Keep the spirit alive ! ♡",newsLimit:4},
sources:{home:[{type:"opml",name:"CoreOS OPML",url:"https://nexgen999.github.io/evoX-CoreOS/rss/source_aio.opml"}],news:[
{type:"rss",name:"Payloads",url:"https://nexgen999.github.io/evoX-CoreOS/rss/payloads_rss.xml"},
{type:"rss",name:"Packages",url:"https://nexgen999.github.io/evoX-CoreOS/rss/pkg_rss.xml"},
{type:"rss",name:"FFPFSC",url:"https://nexgen999.github.io/evoX-CoreOS/rss/ffpfsc_rss.xml"},
{type:"rss",name:"Applications",url:"https://nexgen999.github.io/evoX-CoreOS/rss/apps_rss.xml"}],
store:[
{name:"Payloads",url:"https://nexgen999.github.io/evoX-CoreOS/json/payloads.json"},
{name:"Packages",url:"https://nexgen999.github.io/evoX-CoreOS/json/pkg.json"},
{name:"FFPFSC",url:"https://nexgen999.github.io/evoX-CoreOS/json/ffpfsc.json"},
{name:"Applications",url:"https://nexgen999.github.io/evoX-CoreOS/json/apps.json"}]},
download:{aio:[
["Payloads AIO","https://github.com/nexgen999/evoX-CoreOS/releases/download/latest/PS5_payloads_aio_latest.zip"],
["PKG AIO","https://github.com/nexgen999/evoX-CoreOS/releases/download/latest/PS5_pkg_aio_latest.zip"],
["FFPFSC AIO","https://github.com/nexgen999/evoX-CoreOS/releases/download/latest/PS5_ffpfsc_aio_latest.zip"],
["Apps AIO","https://github.com/nexgen999/evoX-CoreOS/releases/download/latest/PS5_apps_aio_latest.zip"],
["Ultimate Pack AIO","https://github.com/nexgen999/evoX-CoreOS/releases/download/latest/PS5_ultimate_pack_latest.zip"]],other:[],catalogues:[
["DLPSGame","https://pegasus-catalog.fly.dev/catalogs/dlps.json"],["Pippo-exfat","https://pegasus-catalog.fly.dev/catalogs/pippo.json"],["PFS catalog","https://pegasus-catalog.fly.dev/catalogs/pfs.json"]]},
services:{defaultIp:"192.168.1.50",tabs:[
{id:"webkit",label:"WebKit",icon:"web",type:"external",items:[]},
{id:"webui",label:"WebUI",icon:"web",type:"ps5",items:[{label:"WebUI principale",port:12800,path:""},{label:"Payload Sender",port:9000,path:""}]},
{id:"scene",label:"Scene sites",icon:"link",type:"external",items:[]},
{id:"custom",label:"Autres",icon:"settings",type:"external",items:[]}]},
documentation:{path:"docs",order:[]},footer:{text:"evoX Core OS · Open Source · Configurable · 2026 · GitHub",badges:[]},
about:{text:"Interface WebUI configurable pour evoX Core OS.",cards:[]},thanks:{text:"Merci à la communauté homebrew, aux développeurs et aux contributeurs.",cards:[]}
};
let C=DEFAULT,S={route:location.hash.slice(1)||"home",news:[],store:[],docs:[],doc:0,tab:0,mode:"tiles",q:"",cat:"",sub:"",ip:""};
const E=s=>esc(s),esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function loadConfig(){try{let r=await fetch("./web/data/config.json",{cache:"no-store"});if(r.ok)C=deep(DEFAULT,await r.json())}catch(e){console.warn(e)}}
function deep(a,b){if(!b||typeof b!=="object")return a;let o=Array.isArray(a)?[...a]:{...a};for(const k in b)o[k]=b[k]&&typeof b[k]==="object"&&!Array.isArray(b[k])?deep(o[k]||{},b[k]):b[k];return o}
async function gh(url){let r=await fetch(url);if(!r.ok)throw Error(r.status);return r.json()}
async function repo(){let g=C.github||{},det=location.hostname.endsWith(".github.io")?location.hostname.split(".")[0]+"/"+location.pathname.split("/").filter(Boolean)[0]:"";let data=g.dataRepository||g.repository||det||"nexgen999/evoX-CoreOS";try{let x=await gh("https://api.github.com/repos/"+data);g.user=g.user||x.owner.login;g.avatar=g.avatar||x.owner.avatar_url;g.repos=g.repos||x.owner.public_repos;g.branch=g.branch||x.default_branch}catch(e){}C.github=g;return data}
async function raw(repo,path,branch){let r=await fetch(`https://raw.githubusercontent.com/${repo}/${branch||"main"}/${path.replace(/^\\//,"")}`);if(!r.ok)throw Error(r.status);return r.text()}
async function feeds(srcs){let out=[];for(const s of srcs||[])try{if((s.type||"rss").toLowerCase()==="opml"){let x=await fetch(s.url).then(r=>r.text()),d=new DOMParser().parseFromString(x,"text/xml");for(const o of d.querySelectorAll("outline[xmlUrl]"))try{out.push(...parseFeed(await fetch(o.getAttribute("xmlUrl")).then(r=>r.text()),o.getAttribute("title")||"OPML"))}catch(e){}}else out.push(...parseFeed(await fetch(s.url).then(r=>r.text()),s.name||"RSS"))}catch(e){console.warn("feed",s.url,e)}return out.sort((a,b)=>new Date(b.date||0)-new Date(a.date||0))}
function parseFeed(x,source){let d=new DOMParser().parseFromString(x,"text/xml");return [...d.querySelectorAll("item,entry")].map(n=>({title:n.querySelector("title")?.textContent||"Sans titre",link:n.querySelector("link")?.getAttribute("href")||n.querySelector("link")?.textContent||"",date:n.querySelector("pubDate")?.textContent||n.querySelector("published")?.textContent||n.querySelector("updated")?.textContent||"",description:n.querySelector("description")?.textContent||n.querySelector("summary")?.textContent||"",source}))}
async function jsonSources(srcs){let a=[];for(const s of srcs||[])try{let d=await fetch(s.url).then(r=>r.json()),x=Array.isArray(d)?d:(d.items||d.files||d.payloads||d.packages||[]);a.push(...x)}catch(e){console.warn("json",s.url,e)}return a}
async function docs(){let repo=C.github.dataRepository||C.github.repository,br=C.github.branch||"main",base=C.documentation.path||"docs",all=[];async function walk(p){let x=await gh(`https://api.github.com/repos/${repo}/contents/${p}?ref=${br}`);for(const n of x)if(n.type==="dir")await walk(n.path);else if(n.type==="file"&&/\\.md$/i.test(n.name))all.push(n.path)}try{await walk(base)}catch(e){}let order=C.documentation.order||[];all.sort((a,b)=>(order.indexOf(a)<0?9999:order.indexOf(a))-(order.indexOf(b)<0?9999:order.indexOf(b))||a.localeCompare(b));return all}
function icon(n,u){return IX.get(n,u)}
function shell(){let g=C.github,h=C.header||{};document.title=C.site.title;document.querySelector("#brand").innerHTML=`<a class="brand-link" href="#home"><img class="logo" src="${E(h.logo)}"><div><div class="brand-name">${E(C.site.name)}</div><div class="brand-sub">${E(h.subtitle||"WEBUI")}</div></div></a>`;document.querySelector("#topActions").innerHTML=(h.actions||[]).map(x=>`<a class="top-btn ${x.iconOnly?"top-icon":""}" href="${E(x.url)}" target="_blank">${icon(x.icon,x.iconUrl)}${x.iconOnly?"":`<span>${E(x.label)}</span>`}</a>`).join("");document.querySelector("#profile").innerHTML=`<div class="profile"><div class="ph"><img class="avatar" src="${E(g.avatar||"./web/assets/avatar-placeholder.svg")}"><div><div class="pn">${E(g.user)}</div><div class="phandle">@${E(g.user)}</div></div></div><div class="bio">${E(g.bio)}</div><div class="meta">◈ ${E(g.repos)} repos · ⌘ GitHub</div></div>`;document.querySelector("#nav").innerHTML=(C.sidebar.menus||[]).map(x=>{let a=Array.isArray(x)?{id:x[0],label:x[1],icon:x[2]}:x;return`<div class="nav ${S.route===a.id?"active":""}" onclick="go('${E(a.id)}')"><span class="ni">${icon(a.icon,a.iconUrl)}</span>${E(a.label)}</div>`}).join("");document.querySelector("#socials").innerHTML=`<div class="social-title">↗ &nbsp;Suivez-moi</div><div class="socials">${(C.socials||[]).map(x=>`<a class="soc" href="${E(x.url)}" target="_blank">${x.iconUrl?`<img src="${E(x.iconUrl)}">`:icon(x.icon)}</a>`).join("")}</div>`;document.querySelector("#sideCard").innerHTML=`<div class="side-card"><b>${E(C.sidebar.card.title)}</b><span>${E(C.sidebar.card.text)}</span></div>`}
function footer(){let f=C.footer||{};return`<div class="footer"><span>${E(f.text||"evoX Core OS")}</span><span class="badges">${(f.badges||[]).map(b=>`<a class="badge" href="${E(b.url)}" target="_blank">${E(b.label)}</a>`).join("")}</span></div>`}
function hero(){let h=C.home.hero;return`<section class="hero"><div class="eyebrow">${E(h.eyebrow)}</div><h1>${E(h.title)}</h1><p>${E(h.text)}</p><div class="chips">${h.chips.map(x=>`<span class="chip">${E(x)}</span>`).join("")}</div></section>`}
async function home(){if(!S.news.length)S.news=await feeds(C.sources.home);if(!S.store.length)S.store=await jsonSources(C.sources.store);let h=C.home,n=S.news.slice(0,h.newsLimit),items=S.store.map(norm),cats=[...new Set(items.map(x=>x.category).filter(Boolean))].slice(0,5);return`<div class="wrap">${hero()}<div class="grid"><section class="panel"><div class="head"><div><div class="title">◔ Dernières News</div><div class="sub">Actualités, mises à jour et infos du moment</div></div><button class="btn" onclick="go('news')">Voir toutes les news →</button></div><div class="body newslist">${n.length?n.map(postMini).join(""):`<div class="empty">Les flux RSS / OPML apparaîtront ici automatiquement.</div>`}</div></section><div class="side"><section class="panel welcome"><div class="body"><h2>👋 ${E(h.welcomeTitle)}</h2><p>${E(h.welcomeText)}<br><br>— ${E(C.github.user)}</p></div></section><section class="panel"><div class="head"><div><div class="title">▣ Store</div><div class="sub">Accédez à tous mes outils et fichiers</div></div></div><div class="body"><input class="search" placeholder="⌕ Rechercher un fichier, un outil..." oninput="S.q=this.value"><div class="filters"><select class="select"><option>Toutes les catégories</option>${cats.map(x=>`<option>${E(x)}</option>`).join("")}</select><select class="select"><option>Toutes les sous-catégories</option></select></div><div class="cats">${cats.map(x=>`<button class="cat">${icon("store")}<br>${E(x)}</button>`).join("")||"<button class=cat>✦<br>Payloads</button><button class=cat>◇<br>Packages</button><button class=cat>⚒<br>Tools</button><button class=cat>▦<br>Applications</button><button class=cat>◈<br>Divers</button>"}</div></div></section><section class="panel"><div class="head"><div class="title">⇩ Ressources Rapides</div></div><div class="body quick">${(C.home.quickResources||C.download.aio.slice(0,2).map(x=>({label:x[0],url:x[1]}))).map(x=>`<a class="q" href="${E(x.url)}"><b>⇩ ${E(x.label)}</b><small>${E(x.sub||"Pack / ressource")}</small></a>`).join("")}</div></section></div></div><div class="thanks"><div><b>♥ ${E(h.thanksTitle)}</b><p>${E(h.thanksText)}</p></div><div class="slogan">${E(h.slogan)}</div></div><div class="stats"><div class="stat"><b>${E(C.github.repos)}</b><span>Dépôts GitHub</span></div><div class="stat"><b>${S.store.length||"—"}</b><span>Fichiers disponibles</span></div><div class="stat"><b>${[...new Set(items.map(x=>x.category).filter(Boolean))].length||"—"}</b><span>Catégories</span></div><div class="stat"><b>● Site en ligne</b><span class="online">Détection automatique activée</span></div></div>${footer()}</div>`}
function postMini(n){return`<article class="news"><div class="newsimg"></div><div><div class="date">◷ ${E(n.date?new Date(n.date).toLocaleDateString("fr-FR"):"")} · ${E(n.source)}</div><h3>${E(n.title)}</h3><p>${E(n.description).slice(0,190)}</p>${n.link?`<a href="${E(n.link)}" target="_blank" style="font-size:10px;color:#00cfff">Lire la suite →</a>`:""}</div></article>`}
async function news(){if(!S.news.length)S.news=await feeds(C.sources.news);return`<div class="wrap"><section class="page"><div class="eyebrow">evoX CORE OS · RSS / ATOM / OPML</div><h1>News</h1><p>Lecteur de flux façon blog. Les sources sont configurables et non limitées artificiellement.</p></section><div class="blog">${S.news.map(n=>`<article class="post"><div class="date">${E(n.source)} · ${E(n.date?new Date(n.date).toLocaleString("fr-FR"):"")}</div><h2>${E(n.title)}</h2><p>${E(n.description).slice(0,900)}</p>${n.link?`<a class="btn primary" href="${E(n.link)}" target="_blank">Lire l'article ↗</a>`:""}</article>`).join("")||`<div class=empty>Aucune actualité. Vérifiez CORS et les URLs RSS/OPML.</div>`}</div>${footer()}</div>`}
function norm(x){return{name:x.name||x.title||x.filename||x.file||"Fichier",description:x.description||x.desc||"",category:x.category||x.type||"Autres",sub:x.subcategory||x.subCategory||"",url:x.url||x.download||x.download_url||x.link||"",icon:x.icon||"▣"}}
async function store(){if(!S.store.length)S.store=await jsonSources(C.sources.store);let a=S.store.map(norm),cats=[...new Set(a.map(x=>x.category))],subs=[...new Set(a.filter(x=>!S.cat||x.category===S.cat).map(x=>x.sub).filter(Boolean))],f=a.filter(x=>(!S.q||`${x.name} ${x.description}`.toLowerCase().includes(S.q.toLowerCase()))&&(!S.cat||x.category===S.cat)&&(!S.sub||x.sub===S.sub));return`<div class="wrap"><section class="page"><div class="eyebrow">evoX CORE OS · UNIVERSAL STORE</div><h1>Store</h1><p>Catalogue web dynamique — JSON, recherche, catégories, sous-catégories et vues liste / tuile.</p></section><div class="toolbar"><input class="search" style="max-width:450px" placeholder="⌕ Rechercher..." value="${E(S.q)}" oninput="S.q=this.value;render()"><select class="select" onchange="S.cat=this.value;S.sub='';render()"><option value="">Toutes les catégories</option>${cats.map(x=>`<option ${x===S.cat?"selected":""}>${E(x)}</option>`).join("")}</select><select class="select" onchange="S.sub=this.value;render()"><option value="">Toutes les sous-catégories</option>${subs.map(x=>`<option ${x===S.sub?"selected":""}>${E(x)}</option>`).join("")}</select><div class="switch"><button class="${S.mode==="tiles"?"on":""}" onclick="S.mode='tiles';render()">▦ Tuiles</button><button class="${S.mode==="list"?"on":""}" onclick="S.mode='list';render()">☷ Liste</button></div></div><div style="font-size:10px;color:#7196a9;margin-top:9px">${f.length} élément(s)</div>${S.mode==="tiles"?`<div class="storegrid">${f.map(x=>item(x)).join("")}</div>`:`<div class="list">${f.map(x=>row(x)).join("")}</div>`}${footer()}</div>`}
function item(x){return`<article class="item"><div class="itemicon">${E(x.icon)}</div><h3>${E(x.name)}</h3><p>${E(x.description)}</p><p style="color:#11bde9;margin-top:5px">${E(x.category)}${x.sub?" · "+E(x.sub):""}</p>${x.url?`<a class="btn primary" href="${E(x.url)}" target="_blank">⇩ Télécharger</a>`:""}</article>`}
function row(x){return`<div class="row"><div class="itemicon">${E(x.icon)}</div><div><h3>${E(x.name)}</h3><span>${E(x.description)}</span></div><div><span>${E(x.category)}${x.sub?" / "+E(x.sub):""}</span></div><div>${x.url?`<a class="btn primary" href="${E(x.url)}" target="_blank">⇩ Télécharger</a>`:""}</div></div>`}
function download(){let d=C.download;return`<div class="wrap"><section class="page"><div class="eyebrow">evoX CORE OS · DOWNLOADS</div><h1>Download</h1><p>Packs AIO, téléchargements complémentaires et catalogues Pegasus.</p></section><div class="twocol"><section class="panel"><div class="head"><div class="title">⇩ Packs AIO</div></div><div class="body">${d.aio.map(x=>`<div class="service" style="margin-bottom:8px"><div class="svcicon">⇩</div><div><h3>${E(x[0])}</h3><p>Pack CoreOS (.zip)</p><a class="btn primary" href="${E(x[1])}">Télécharger</a></div></div>`).join("")}</div></section><section class="panel"><div class="head"><div class="title">▣ Other Downloads</div></div><div class="body">${d.other.length?d.other.map(x=>`<div class=card><h2>${E(x.label)}</h2><p>${E(x.description)}</p><a class="btn primary" href="${E(x.url)}">Ouvrir</a></div>`).join(""):`<div class=empty>Ajoutez vos téléchargements dans download.other.</div>`}</div></section></div><section class="panel" style="margin-top:12px"><div class="head"><div class="title">⧉ Catalogues Pegasus / DLPSGame</div></div><div class="body">${d.catalogues.map(x=>`<div class="service" style="margin-bottom:8px"><div class=svcicon>⧉</div><div style="flex:1"><h3>${E(x[0])}</h3><p style="word-break:break-all">${E(x[1])}</p><button class="btn primary" onclick="copy('${E(x[1])}')">Copier</button></div></div>`).join("")}</div></section>${footer()}</div>`}
function services(){let d=C.services,t=d.tabs[S.tab]||d.tabs[0];return`<div class="wrap"><section class="page"><div class="eyebrow">evoX CORE OS · SERVICES</div><h1>Services</h1><p>Services externes, WebKit, WebUI locale, sites scène et onglets futurs.</p></section><div class=service-tabs>${d.tabs.map((x,i)=>`<button class="stab ${i===S.tab?"on":""}" onclick="S.tab=${i};render()">${icon(x.icon)} ${E(x.label)}</button>`).join("")}</div><div style="display:flex;align-items:center;margin-top:13px"><h2 style="font-size:17px">${E(t.label)}</h2>${t.type==="ps5"?`<div class=ip>◎ IP console <input value="${E(S.ip||d.defaultIp)}" onchange="S.ip=this.value"></div>`:""}</div><div class=servicegrid>${(t.items||[]).map(x=>{let href=t.type==="ps5"?`http://${S.ip||d.defaultIp}:${x.port}/${String(x.path||"").replace(/^\\//,"")}`:x.url;return`<article class=service><div class=svcicon>${icon("link",x.iconUrl)}</div><div><h3>${E(x.label)}</h3><p>${E(x.description||"")}</p>${x.port?`<p>Port ${E(x.port)}</p>`:""}<a class="btn primary" href="${E(href)}" target="_blank">Ouvrir ↗</a></div></article>`}).join("")}</div>${footer()}</div>`}
async function documentation(){if(!S.docs.length)S.docs=await docs();let p=S.docs[S.doc];if(!p)return`<div class=empty>Aucun fichier Markdown trouvé dans ${E(C.documentation.path)}.</div>`;let md="";try{md=await raw(C.github.dataRepository||C.github.repository,p,C.github.branch||"main")}catch(e){md="# Erreur\\n\\nImpossible de lire ce document.";};return`<div class="wrap"><section class="page"><div class="eyebrow">evoX CORE OS · WIKI</div><h1>Documentation</h1><p>Markdown, sous-dossiers et ordre configurable.</p></section><div class=doclayout><aside class=docnav>${S.docs.map((x,i)=>`<div class="doclink ${i===S.doc?"on":""}" onclick="S.doc=${i};render()">${E(x.replace(/^docs\\//,""))}</div>`).join("")}</aside><article class=article>${MD.render(md)}</article></div>${footer()}</div>`}
function simple(type){let x=C()[type];return`<div class="wrap"><section class=page><div class=eyebrow>evoX CORE OS · ${type.toUpperCase()}</div><h1>${type==="thanks"?"Remerciements":"About"}</h1><p>${E(x.text)}</p></section><div class=twocol>${(x.cards||[]).map(c=>`<section class=card><h2>${icon(c.icon||"link")} ${E(c.title)}</h2><p>${E(c.text)}</p></section>`).join("")}</div>${footer()}</div>`}
async function render(){shell();let v=document.querySelector("#view");v.innerHTML="<div class=empty>Chargement…</div>";try{v.innerHTML=S.route==="home"?await home():S.route==="news"?await news():S.route==="download"?download():S.route==="store"?await store():S.route==="services"?services():S.route==="docs"?await documentation():simple(S.route==="about"?"about":"thanks")}catch(e){console.error(e);v.innerHTML=`<div class=empty>Impossible de charger cette section.<br><br>${E(e.message)}</div>`}}
function go(x){S.route=x;location.hash=x;render()}async function copy(x){try{await navigator.clipboard.writeText(x);alert("URL copiée")}catch(e){prompt("Copier cette URL :",x)}}window.go=go;window.render=render;window.copy=copy;window.S=S;
window.addEventListener("hashchange",()=>{S.route=location.hash.slice(1)||"home";render()});
window.addEventListener("load",async()=>{await loadConfig();await repo();C.github.avatar=C.github.avatar||"./web/assets/avatar-placeholder.svg";render()});
