/* evoX Core OS WebUI - dependency-free client-side engine. */
const DEFAULT = {
  github:{repository:'nexgen999/evoX-CoreOS',dataRepository:'nexgen999/evoX-CoreOS',webuiRepository:'nexgen999/evoX-CoreOS-WebUI',branch:'main',user:'nexgen999',bio:'Passionné par le homebrew, le développement et les projets open source.',repos:''},
  site:{name:'evoX Core OS',title:'evoX Core OS · WebUI'},
  header:{logo:'./web/assets/logo.svg',subtitle:'WEBUI',actions:[]},
  sidebar:{menus:[['home','Home','home'],['news','News','news'],['download','Download','download'],['store','Store','store'],['services','Services','services'],['docs','Documentation','docs'],['about','About','about'],['thanks','Remerciements','thanks']],card:{title:'evoX Core OS',text:'One place. All your needs.'}},
  socials:[],
  home:{hero:{eyebrow:'evoX CORE OS',title:'Bienvenue sur evoX Core OS',text:'Un espace unique pour accéder à mes projets, ressources, news et bien plus encore. Explore, télécharge, découvre !',chips:['✦ Payloads PS5','▣ Store','◔ News RSS','▤ Documentation','◇ Open Source']},welcomeTitle:'Bienvenue !',welcomeText:'Passionné par le homebrew, le développement et les projets open source.',thanksTitle:'Un immense merci !',thanksText:'Merci à toutes les personnes qui me soutiennent, qui m’encouragent et qui font vivre cette communauté. Vous êtes géniaux !',slogan:'Keep the spirit alive ! ♡',newsLimit:4,quickResources:[]},
  sources:{home:[],news:[],store:[]},
  download:{aio:[],other:[],catalogues:[]},
  services:{defaultIp:'127.0.0.1',tabs:[]},
  documentation:{path:'docs',order:[]},
  footer:{text:'evoX Core OS · Open Source · Configurable',badges:[]},
  about:{text:'Interface WebUI configurable pour evoX Core OS.',cards:[]},
  thanks:{text:'Merci à la communauté homebrew, aux développeurs et aux contributeurs.',cards:[]}
};
let C=clone(DEFAULT);
const S={route:location.hash.slice(1)||'home',news:[],store:[],docs:[],doc:0,tab:0,mode:'tiles',q:'',cat:'',sub:'',ip:''};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clone=o=>JSON.parse(JSON.stringify(o));
function merge(a,b){if(!b||typeof b!=='object')return a;for(const k of Object.keys(b)){if(b[k]&&typeof b[k]==='object'&&!Array.isArray(b[k]))a[k]=merge(a[k]&&typeof a[k]==='object'?a[k]:{},b[k]);else a[k]=b[k]}return a}
function timeout(ms){return new Promise((_,rej)=>setTimeout(()=>rej(new Error('timeout')),ms))}
async function fetchText(url,ms=7000){const r=await Promise.race([fetch(url,{cache:'no-store'}),timeout(ms)]);if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return r.text()}
async function fetchJson(url,ms=7000){return JSON.parse(await fetchText(url,ms))}
async function loadConfig(){try{const x=await fetchJson('./web/data/config.json',5000);C=merge(clone(DEFAULT),x)}catch(e){console.warn('Configuration locale indisponible, utilisation des valeurs par défaut.',e)}}
function detectRepo(){const p=location.pathname.split('/').filter(Boolean);return location.hostname.endsWith('.github.io')&&p[0]?`${location.hostname.split('.')[0]}/${p[0]}`:null}
async function detectGitHub(){const g=C.github||{};const repo=g.repository||detectRepo()||'nexgen999/evoX-CoreOS';try{const x=await fetchJson(`https://api.github.com/repos/${repo}`,5000);g.user=g.user||x.owner?.login;g.avatar=g.avatar||x.owner?.avatar_url;g.repos=g.repos||x.owner?.public_repos;g.branch=g.branch||x.default_branch}catch(e){console.warn('GitHub API indisponible, configuration locale conservée.',e)}C.github=g}
function repoRaw(path){const repo=C.github.dataRepository||C.github.repository;const br=C.github.branch||'main';return `https://raw.githubusercontent.com/${repo}/${br}/${String(path).replace(/^\/+/, '')}`}
function parseFeed(xml,source){const d=new DOMParser().parseFromString(xml,'text/xml');if(d.querySelector('parsererror'))return[];return [...d.querySelectorAll('item,entry')].map(n=>({title:n.querySelector('title')?.textContent?.trim()||'Sans titre',link:n.querySelector('link')?.getAttribute('href')||n.querySelector('link')?.textContent?.trim()||'',date:n.querySelector('pubDate')?.textContent||n.querySelector('published')?.textContent||n.querySelector('updated')?.textContent||'',description:n.querySelector('description')?.textContent||n.querySelector('summary')?.textContent||'',source}));}
async function feeds(sources){const out=[];for(const s of sources||[]){try{if(String(s.type||'rss').toLowerCase()==='opml'){const xml=await fetchText(s.url);const d=new DOMParser().parseFromString(xml,'text/xml');for(const o of d.querySelectorAll('outline[xmlUrl]')){try{out.push(...parseFeed(await fetchText(o.getAttribute('xmlUrl')),o.getAttribute('title')||s.name||'OPML'))}catch(e){console.warn('Flux OPML ignoré:',e)}}}else out.push(...parseFeed(await fetchText(s.url),s.name||'RSS'))}catch(e){console.warn('Source RSS ignorée:',s.url,e)}}return out.sort((a,b)=>new Date(b.date||0)-new Date(a.date||0));}
async function jsonSources(sources){const out=[];for(const s of sources||[]){try{const d=await fetchJson(s.url);const x=Array.isArray(d)?d:(d.items||d.files||d.payloads||d.packages||d.data||[]);if(Array.isArray(x))out.push(...x)}catch(e){console.warn('JSON ignoré:',s.url,e)}}return out}
function norm(x){return{name:x.name||x.title||x.filename||x.file||'Fichier',description:x.description||x.desc||'',category:x.category||x.type||'Autres',sub:x.subcategory||x.subCategory||'',url:x.url||x.download||x.download_url||x.link||'',icon:x.icon||'▣'}}
function icon(n,u){return IX.get(n,u)}
function normalizeDownload(x){if(Array.isArray(x))return{label:x[0],url:x[1],description:'Pack CoreOS (.zip)'};return x||{}}
function shell(){const g=C.github||{},h=C.header||{};document.title=C.site.title||'evoX Core OS';document.querySelector('#brand').innerHTML=`<a class="brand-link" href="#home"><img class="logo" src="${esc(h.logo||'./web/assets/logo.svg')}" alt=""><div><div class="brand-name">${esc(C.site.name)}</div><div class="brand-sub">${esc(h.subtitle||'WEBUI')}</div></div></a>`;document.querySelector('#topActions').innerHTML=(h.actions||[]).map(x=>`<a class="top-btn ${x.iconOnly?'top-icon':''}" href="${esc(x.url||'#')}" target="_blank" rel="noopener">${icon(x.icon,x.iconUrl)}${x.iconOnly?'':`<span>${esc(x.label)}</span>`}</a>`).join('');document.querySelector('#profile').innerHTML=`<div class="profile"><div class="ph"><img class="avatar" src="${esc(g.avatar||'./web/assets/avatar-placeholder.svg')}" alt=""><div><div class="pn">${esc(g.user||'GitHub')}</div><div class="phandle">@${esc(g.user||'')}</div></div></div><div class="bio">${esc(g.bio||'')}</div><div class="meta">◈ ${esc(g.repos||'—')} repos · ⌘ GitHub</div></div>`;document.querySelector('#nav').innerHTML=(C.sidebar.menus||[]).map(x=>{const a=Array.isArray(x)?{id:x[0],label:x[1],icon:x[2]}:x;return`<div class="nav ${S.route===a.id?'active':''}" data-route="${esc(a.id)}"><span class="ni">${icon(a.icon,a.iconUrl)}</span>${esc(a.label)}</div>`}).join('');document.querySelectorAll('#nav .nav').forEach(n=>n.addEventListener('click',()=>go(n.dataset.route)));document.querySelector('#socials').innerHTML=`<div class="social-title">↗ &nbsp;Suivez-moi</div><div class="socials">${(C.socials||[]).map(x=>`<a class="soc" href="${esc(x.url||'#')}" target="_blank" rel="noopener" title="${esc(x.label)}">${x.iconUrl?`<img src="${esc(x.iconUrl)}" alt="">`:icon(x.icon)}</a>`).join('')}</div>`;document.querySelector('#sideCard').innerHTML=`<div class="side-card"><b>${esc(C.sidebar.card?.title||'evoX Core OS')}</b><span>${esc(C.sidebar.card?.text||'One place. All your needs.')}</span></div>`}
function footer(){const f=C.footer||{};return`<div class="footer"><span>${esc(f.text||'evoX Core OS')}</span><span class="badges">${(f.badges||[]).map(b=>`<a class="badge" href="${esc(b.url)}" target="_blank" rel="noopener">${esc(b.label)}</a>`).join('')}</span></div>`}
function hero(){const h=C.home.hero||{};return`<section class="hero"><div class="eyebrow">${esc(h.eyebrow)}</div><h1>${esc(h.title)}</h1><p>${esc(h.text)}</p><div class="chips">${(h.chips||[]).map(x=>`<span class="chip">${esc(x)}</span>`).join('')}</div></section>`}
function postMini(n){return`<article class="news"><div class="newsimg"></div><div><div class="date">◷ ${esc(n.date?new Date(n.date).toLocaleDateString('fr-FR'):'')} · ${esc(n.source)}</div><h3>${esc(n.title)}</h3><p>${esc(n.description).slice(0,190)}</p>${n.link?`<a href="${esc(n.link)}" target="_blank" rel="noopener" style="font-size:10px;color:#00cfff">Lire la suite →</a>`:''}</div></article>`}
function localSampleNews(){return[]}
async function home(){const h=C.home;const n=(S.news.length?S.news:localSampleNews()).slice(0,h.newsLimit||4);const items=S.store.map(norm);const cats=[...new Set(items.map(x=>x.category).filter(Boolean))].slice(0,5);return`<div class="wrap">${hero()}<div class="grid"><section class="panel"><div class="head"><div><div class="title">◔ Dernières News</div><div class="sub">Actualités, mises à jour et infos du moment</div></div><button class="btn" onclick="go('news')">Voir toutes les news →</button></div><div class="body newslist">${n.length?n.map(postMini).join(''):`<div class="empty">Les flux RSS / OPML apparaîtront ici automatiquement.<br><small>Chargement des sources configurées…</small></div>`}</div></section><div class="side"><section class="panel welcome"><div class="body"><h2>👋 ${esc(h.welcomeTitle)}</h2><p>${esc(h.welcomeText)}<br><br>— ${esc(C.github.user||'nexgen999')}</p></div></section><section class="panel"><div class="head"><div><div class="title">▣ Store</div><div class="sub">Accédez à tous mes outils et fichiers</div></div></div><div class="body"><input class="search" placeholder="⌕ Rechercher un fichier, un outil..." oninput="S.q=this.value"><div class="filters"><select class="select"><option>Toutes les catégories</option>${cats.map(x=>`<option>${esc(x)}</option>`).join('')}</select><select class="select"><option>Toutes les sous-catégories</option></select></div><div class="cats">${(cats.length?cats:['Payloads','Packages','FFPFSC','Applications','Tools']).map(x=>`<button class="cat">${icon('store')}<br>${esc(x)}<br><small>(${items.filter(i=>i.category===x).length})</small></button>`).join('')}</div></div></section><section class="panel"><div class="head"><div class="title">⇩ Ressources Rapides</div></div><div class="body quick">${(h.quickResources||[]).map(x=>`<a class="q" href="${esc(x.url)}"><b>⇩ ${esc(x.label)}</b><small>${esc(x.sub||'Ressource')}</small></a>`).join('')}</div></section></div></div><div class="thanks"><div><b>♥ ${esc(h.thanksTitle)}</b><p>${esc(h.thanksText)}</p></div><div class="slogan">${esc(h.slogan)}</div></div><div class="stats"><div class="stat"><b>${esc(C.github.repos||'—')}</b><span>Dépôts GitHub</span></div><div class="stat"><b>${S.store.length||'—'}</b><span>Fichiers disponibles</span></div><div class="stat"><b>${[...new Set(items.map(x=>x.category).filter(Boolean))].length||'—'}</b><span>Catégories</span></div><div class="stat"><b>● Site en ligne</b><span class="online">Détection automatique activée</span></div></div>${footer()}</div>`}
async function news(){if(!S.news.length)S.news=await feeds(C.sources.news);return`<div class="wrap"><section class="page"><div class="eyebrow">evoX CORE OS · RSS / ATOM / OPML</div><h1>News</h1><p>Lecteur de flux façon blog. Les sources RSS, Atom et OPML sont configurables sans limite artificielle.</p></section><div class="blog">${S.news.map(n=>`<article class="post"><div class="date">${esc(n.source)} · ${esc(n.date?new Date(n.date).toLocaleString('fr-FR'):'')}</div><h2>${esc(n.title)}</h2><p>${esc(n.description).slice(0,900)}</p>${n.link?`<a class="btn primary" href="${esc(n.link)}" target="_blank" rel="noopener">Lire l'article ↗</a>`:''}</article>`).join('')||`<div class="empty">Aucune actualité chargée. Vérifiez les URLs et les autorisations CORS des flux.</div>`}</div>${footer()}</div>`}
async function store(){if(!S.store.length)S.store=await jsonSources(C.sources.store);const a=S.store.map(norm),cats=[...new Set(a.map(x=>x.category))],subs=[...new Set(a.filter(x=>!S.cat||x.category===S.cat).map(x=>x.sub).filter(Boolean))],f=a.filter(x=>(!S.q||`${x.name} ${x.description}`.toLowerCase().includes(S.q.toLowerCase()))&&(!S.cat||x.category===S.cat)&&(!S.sub||x.sub===S.sub));return`<div class="wrap"><section class="page"><div class="eyebrow">evoX CORE OS · UNIVERSAL STORE</div><h1>Store</h1><p>Catalogue web dynamique — JSON, recherche, catégories, sous-catégories et vues liste / tuile.</p></section><div class="toolbar"><input class="search" style="max-width:450px" placeholder="⌕ Rechercher..." value="${esc(S.q)}" oninput="S.q=this.value;render()"><select class="select" onchange="S.cat=this.value;S.sub='';render()"><option value="">Toutes les catégories</option>${cats.map(x=>`<option value="${esc(x)}" ${x===S.cat?'selected':''}>${esc(x)}</option>`).join('')}</select><select class="select" onchange="S.sub=this.value;render()"><option value="">Toutes les sous-catégories</option>${subs.map(x=>`<option value="${esc(x)}" ${x===S.sub?'selected':''}>${esc(x)}</option>`).join('')}</select><div class="switch"><button class="${S.mode==='tiles'?'on':''}" onclick="S.mode='tiles';render()">▦ Tuiles</button><button class="${S.mode==='list'?'on':''}" onclick="S.mode='list';render()">☷ Liste</button></div></div><div style="font-size:10px;color:#7196a9;margin-top:9px">${f.length} élément(s)</div>${S.mode==='tiles'?`<div class="storegrid">${f.map(item).join('')}</div>`:`<div class="list">${f.map(row).join('')}</div>`}${footer()}</div>`}
function item(x){return`<article class="item"><div class="itemicon">${esc(x.icon)}</div><h3>${esc(x.name)}</h3><p>${esc(x.description)}</p><p style="color:#11bde9;margin-top:5px">${esc(x.category)}${x.sub?' · '+esc(x.sub):''}</p>${x.url?`<a class="btn primary" href="${esc(x.url)}" target="_blank" rel="noopener">⇩ Télécharger</a>`:''}</article>`}
function row(x){return`<div class="row"><div class="itemicon">${esc(x.icon)}</div><div><h3>${esc(x.name)}</h3><span>${esc(x.description)}</span></div><div><span>${esc(x.category)}${x.sub?' / '+esc(x.sub):''}</span></div><div>${x.url?`<a class="btn primary" href="${esc(x.url)}" target="_blank" rel="noopener">⇩ Télécharger</a>`:''}</div></div>`}
function download(){const d=C.download||{};const aio=(d.aio||[]).map(normalizeDownload);return`<div class="wrap"><section class="page"><div class="eyebrow">evoX CORE OS · DOWNLOADS</div><h1>Download</h1><p>Packs AIO, téléchargements complémentaires et catalogues Pegasus.</p></section><div class="twocol"><section class="panel"><div class="head"><div class="title">⇩ Packs AIO</div></div><div class="body">${aio.map(x=>`<div class="service" style="margin-bottom:8px"><div class="svcicon">⇩</div><div><h3>${esc(x.label)}</h3><p>${esc(x.description||'Pack CoreOS (.zip)')}</p><a class="btn primary" href="${esc(x.url)}">Télécharger</a></div></div>`).join('')}</div></section><section class="panel"><div class="head"><div class="title">▣ Other Downloads</div></div><div class="body">${(d.other||[]).map(x=>`<div class="card"><h2>${esc(x.label)}</h2><p>${esc(x.description)}</p><a class="btn primary" href="${esc(x.url)}" target="_blank" rel="noopener">Télécharger</a></div>`).join('')||'<div class="empty">Ajoutez vos téléchargements dans download.other.</div>'}</div></section></div><section class="panel" style="margin-top:12px"><div class="head"><div class="title">⧉ Catalogues Pegasus / DLPSGame</div></div><div class="body">${(d.catalogues||[]).map(x=>`<div class="service" style="margin-bottom:8px"><div class="svcicon">⧉</div><div style="flex:1"><h3>${esc(x.label)}</h3><p style="word-break:break-all">${esc(x.url)}</p><button class="btn primary" onclick="copyUrl('${esc(x.url)}')">Copier</button></div></div>`).join('')}</div></section>${footer()}</div>`}
function services(){const d=C.services||{},tabs=d.tabs||[],t=tabs[S.tab]||tabs[0]||{label:'Services',items:[]};return`<div class="wrap"><section class="page"><div class="eyebrow">evoX CORE OS · SERVICES</div><h1>Services</h1><p>Services externes, WebKit, WebUI locale, sites scène et onglets futurs.</p></section><div class="service-tabs">${tabs.map((x,i)=>`<button class="stab ${i===S.tab?'on':''}" onclick="S.tab=${i};render()">${icon(x.icon)} ${esc(x.label)}</button>`).join('')}</div><div style="display:flex;align-items:center;margin-top:13px"><h2 style="font-size:17px">${esc(t.label||'Services')}</h2>${t.type==='ps5'?`<div class="ip">◎ IP console <input value="${esc(S.ip||d.defaultIp||'127.0.0.1')}" onchange="S.ip=this.value"></div>`:''}</div><div class="servicegrid">${(t.items||[]).map(x=>{const href=t.type==='ps5'?`http://${S.ip||d.defaultIp||'127.0.0.1'}:${x.port}${String(x.path||'').startsWith('/')?x.path:'/'+String(x.path||'')}`:x.url;return`<article class="service"><div class="svcicon">${icon(x.icon||'link',x.iconUrl)}</div><div><h3>${esc(x.label)}</h3><p>${esc(x.description||'')}</p>${x.port?`<p>Port ${esc(x.port)}</p>`:''}<a class="btn primary" href="${esc(href||'#')}" target="_blank" rel="noopener">Ouvrir ↗</a></div></article>`}).join('')}</div>${footer()}</div>`}
async function documentation(){if(!S.docs.length)S.docs=await discoverDocs();const p=S.docs[S.doc];if(!p)return`<div class="wrap"><div class="empty">Aucun fichier Markdown trouvé dans ${esc(C.documentation.path||'docs')}.</div>${footer()}</div>`;let md='# Documentation';try{md=await fetchText(repoRaw(p))}catch(e){md='# Erreur de lecture\n\nImpossible de lire ce document depuis GitHub.'}return`<div class="wrap"><section class="page"><div class="eyebrow">evoX CORE OS · WIKI</div><h1>Documentation</h1><p>Wiki Markdown avec sous-dossiers et ordre configurable.</p></section><div class="doclayout"><aside class="docnav">${S.docs.map((x,i)=>`<div class="doclink ${i===S.doc?'on':''}" onclick="S.doc=${i};render()">${esc(x.replace(/^docs\//,''))}</div>`).join('')}</aside><article class="article">${MD.render(md)}</article></div>${footer()}</div>`}
async function discoverDocs(){const repo=C.github.dataRepository||C.github.repository,br=C.github.branch||'main',base=C.documentation.path||'docs',all=[];async function walk(p){const x=await fetchJson(`https://api.github.com/repos/${repo}/contents/${encodeURIComponent(p).replace(/%2F/g,'/')}?ref=${encodeURIComponent(br)}`,5000);for(const n of x||[])if(n.type==='dir')await walk(n.path);else if(n.type==='file'&&/\.md$/i.test(n.name))all.push(n.path)}try{await walk(base)}catch(e){console.warn('Documentation GitHub indisponible.',e)}const order=C.documentation.order||[];return all.sort((a,b)=>{const ai=order.indexOf(a),bi=order.indexOf(b);return(ai<0?9999:ai)-(bi<0?9999:bi)||a.localeCompare(b)})}
function simple(type){const x=C[type]||{};return`<div class="wrap"><section class="page"><div class="eyebrow">evoX CORE OS · ${type.toUpperCase()}</div><h1>${type==='thanks'?'Remerciements':'About'}</h1><p>${esc(x.text||'')}</p></section><div class="twocol">${(x.cards||[]).map(c=>`<section class="card"><h2>${icon(c.icon||'link')} ${esc(c.title)}</h2><p>${esc(c.text)}</p></section>`).join('')}</div>${footer()}</div>`}
async function render(){shell();const v=document.querySelector('#view');v.innerHTML='<div class="empty">Chargement…</div>';try{if(S.route==='home')v.innerHTML=await home();else if(S.route==='news')v.innerHTML=await news();else if(S.route==='download')v.innerHTML=download();else if(S.route==='store')v.innerHTML=await store();else if(S.route==='services')v.innerHTML=services();else if(S.route==='docs')v.innerHTML=await documentation();else v.innerHTML=simple(S.route==='about'?'about':'thanks')}catch(e){console.error(e);v.innerHTML=`<div class="empty">Impossible de charger cette section.<br><br>${esc(e.message)}</div>`}}
function go(x){S.route=x;location.hash=x;render()}
async function copyUrl(x){try{await navigator.clipboard.writeText(x);alert('URL copiée')}catch(e){prompt('Copier cette URL :',x)}}
window.go=go;window.render=render;window.copyUrl=copyUrl;window.S=S;
window.addEventListener('hashchange',()=>{S.route=location.hash.slice(1)||'home';render()});
window.addEventListener('load',async()=>{await loadConfig();await detectGitHub();C.github.avatar=C.github.avatar||'./web/assets/avatar-placeholder.svg';shell();await render();/* Data refresh happens after the shell is visible. */Promise.all([feeds(C.sources.home),jsonSources(C.sources.store)]).then(([n,st])=>{S.news=n;S.store=st;render()}).catch(e=>console.warn('Actualisation des données:',e));});
