function text(el,sel){return el?.querySelector(sel)?.textContent?.trim()||'';}
function firstText(el,sels){for(const s of sels){const v=text(el,s);if(v)return v;}return '';}
function parseXML(xml,source='RSS'){const doc=new DOMParser().parseFromString(xml,'application/xml');if(doc.querySelector('parsererror'))throw new Error('XML invalide');const nodes=[...doc.querySelectorAll('item, entry')];return nodes.map(n=>{const linkEl=n.querySelector('link');let link=linkEl?.getAttribute('href')||linkEl?.textContent?.trim()||'';const desc=firstText(n,['description','summary','content','content\\:encoded']);let image=n.querySelector('media\\:content, media\\:thumbnail')?.getAttribute('url')||n.querySelector('enclosure[type^="image"]')?.getAttribute('url')||'';if(!image){const m=desc.match(/<img[^>]+src=["']([^"']+)/i);if(m)image=m[1];}return {title:firstText(n,['title'])||'Sans titre',description:desc.replace(/<[^>]+>/g,' ').replace(/\\s+/g,' ').trim(),link,date:firstText(n,['pubDate','published','updated','dc\\:date']),source,image};}).filter(x=>x.title);}
function parseOPML(xml){const doc=new DOMParser().parseFromString(xml,'application/xml');return [...doc.querySelectorAll('outline[xmlUrl],outline[xmlurl]')].map(o=>({url:o.getAttribute('xmlUrl')||o.getAttribute('xmlurl'),label:o.getAttribute('title')||o.getAttribute('text')||'OPML'})).filter(x=>x.url);}
async function get(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`${r.status} ${url}`);return r.text();}
function abs(u){return /^https?:\/\//i.test(u)?u:new URL(u,location.href).href;}
async function discover(cfg){const out=[];const base=cfg.repository?.apiBase||'https://api.github.com';if(!cfg.repository?.owner||!cfg.repository?.name)return out;const path=(cfg.paths?.rssDir||'/rss/').replace(/^\//,'').replace(/\/$/,'');try{const r=await fetch(`${base}/repos/${cfg.repository.owner}/${cfg.repository.name}/contents/${path}?ref=${encodeURIComponent(cfg.repository.branch==='auto'?'main':cfg.repository.branch||'main')}`);if(r.ok){const j=await r.json();for(const x of j||[])if(x.type==='file'&&/\.(xml|rss|atom)$/i.test(x.name))out.push({url:x.download_url,label:x.name});}}catch(e){}return out;}
export async function readAllFeeds(cfg,section={}){if(section.enabled===false)return {items:[],errors:[]};const sources=[],seen=new Set();const add=(url,label)=>{if(url&&!seen.has(url)){seen.add(url);sources.push({url,label});}};for(const f of section.feeds||[])if(f.enabled!==false)add(f.url,f.label);for(const f of section.opmlFiles||[]){try{for(const x of parseOPML(await get(abs(f))))add(x.url,x.label);}catch(e){}}if(section.autoDiscoverOpml){for(const f of cfg.rss?.opmlFiles||[])try{for(const x of parseOPML(await get(abs(f))))add(x.url,x.label);}catch(e){}}
  if(section.autoDiscover){for(const x of await discover(cfg))add(x.url,x.label);}
  const items=[],errors=[];for(const s of sources){try{const xml=await get(abs(s.url));if(/<opml[\s>]/i.test(xml.slice(0,500))){for(const x of parseOPML(xml)){try{items.push(...parseXML(await get(abs(x.url)),x.label));}catch(e){errors.push(`${x.url}: ${e.message}`);}}}else items.push(...parseXML(xml,s.label||new URL(abs(s.url)).hostname));}catch(e){errors.push(`${s.url}: ${e.message}`);}}
  items.sort((a,b)=>new Date(b.date)-new Date(a.date));const unique=[],seenItems=new Set();for(const x of items){const k=(x.link||x.title).toLowerCase();if(!seenItems.has(k)){seenItems.add(k);unique.push(x);}}return {items:unique.slice(0,section.maxItems||200),errors};}
